name: ti_bank
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar: ^5.0.2
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.0
  smooth_page_indicator: ^1.1.0
  overlay_support: ^2.1.0
  flutter_inappwebview: ^5.8.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^9.8.0+1
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  in_app_review: ^2.0.6
  dio: ^5.3.2
  go_router: ^12.0.0
  
  json_annotation: ^4.8.1

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/bot/
    - assets/income_source/
    - assets/